import Header from "components/header";
import Cards from "components/cards";
import Tiles from "components/tiles";
import Footer from "components/footer";
import first from "assets/tiles/first.png";
import second from "assets/tiles/second.png";
import third from "assets/tiles/third.png";
import fourth from "assets/tiles/fourth.png";
import Search from "assets/cards/Search";
import Select from "assets/cards/Select";
import StandOut from "assets/cards/StandOut";

function App() {
  const cardsData = [
    {
      icon: Search,
      heading: "Search",
      content:
        "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
    },
    {
      icon: Select,
      heading: "Select",
      content:
        "Choose from thousands of options generated by the slogan maker that fit your needs.",
    },
    {
      icon: StandOut,
      heading: "Stand Out",
      content: "Congrats on your new slogan. It's time to win the world!",
    },
  ];

  const tilesData = [
    {
      image: first,
      subHeading: "Privacy Policy Generator",
      content:
        "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
    {
      image: second,
      subHeading: "Terms & Conditions Generator",
      content:
        "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
    {
      image: third,
      subHeading: "Domain Name Generator",
      content:
        "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
    {
      image: fourth,
      subHeading: "Invoice Generator",
      content:
        "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
  ];

  return (
    <div className="App">
      <Header />
      <Cards data={cardsData} />
      <Tiles data={tilesData} />
      <Footer />
    </div>
  );
}

export default App;
